[package]
name = "v8_promise_reject_test"
version = "0.1.0"
authors = ["Monroe Clinton"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_v8 = "0.12.0"